name: build-test-extension
on: [push]
jobs:
  build-extension-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '23'
      - run: npm --version
      - run: node --version
      - run: npm ci
      - run: npm run compile

  test-extension-frontend:
    needs: build-extension-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm --version
      - run: node --version
      - run: npm ci
      - run: xvfb-run -a npm test


